package com.sport.support.MemberPackage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController    // This means that this class is a Controller
@RequestMapping(path="/member") // This means URL's start with /demo (after Application path)
public class memberController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private memberRepository memberRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewMember (@RequestParam String username
			, @RequestParam String mail) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		System.out.println("hey it is saved");
		member n = new member(username,mail,3,5);
		memberRepository.save(n);
		return "hey it is saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<member> getAllMembers() {
		// This returns a JSON or XML with the users
		return memberRepository.findAll();
	}
	
}
